[build]
  command   = "npm run build"
  

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = [".next/*.json"]
  external_node_modules = ["gsap"]
  node_bundler = "esbuild"