[build]
  command   = "yarn build"
  environment = { NETLIFY_USE_YARN = "true" }
  publish   = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = [".next/*.json"]
  external_node_modules = ["gsap"]